name: action name # 这里是描述这个action的名字
on: # action的触发条件，比如手动、定时、收到push事件等
  workflow_dispatch: # 这个表示，该action可以手动触发
  schedule: # 定时调度规则
    - cron: '*/30 * * * *'
jobs: # 开始定义要执行的任务
  first: # 任务的名称，这个‘first’可以自定义名字
    runs-on: unbuntu-latest # 需要依赖于什么环境运行，参考官网https://docs.github.com/en/actions/using-jobs/choosing-the-runner-for-a-job
    steps: # 开始定义任务执行的步骤
      - name: set env # 步骤的名字
        run: | # 这一步骤的脚本，可以直接sudo执行命令，环境中的默认用户名是runner，下面这个脚本就是修改runner的默认密码
          sudo apt update
          sudo apt -y install sshpass
          sudo passwd runner << EOD
          root
          root
          EOD
      - name: step2
      ....
